# Add your OpenAI API key here
OPENAI_API_KEY = "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"
